# NUMPY (Numerical Python) Library
Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

A NumPy array (ndarray) is a collection of elements of the same data type stored in a multidimensional structure. Arrays provide an efficient way to store and perform operations on numerical data.

Number of dimensions in an array is called its rank.
Size of the array along each dimension is called its shape.
Elements are accessed using square brackets [] and arrays are commonly created from Python lists.

In [4]:
import numpy as np
print(np.__version__)


2.3.5


# Arrays

In [5]:
a = [1,2,3,4,5]
import numpy as np
b = np.array([1,2,3,4,5])
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [7]:
b = np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


# All zeros and ones Array

In [9]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [10]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


# Arrange format

In [13]:
import numpy as np
b = np.arange(0,10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


# Multi-Dimentional Array

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [7 8 9]]


In [18]:
arr = np.array([1,2,3,4], ndmin=8)
print(arr)

[[[[[[[[1 2 3 4]]]]]]]]


# Chexk array dimensions

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9],[7,8,9]])
print(arr.ndim)

2


# Shape and size

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


# Indexing and slicing of array

In [22]:
arr = np.array([10,20,30,40])
print(arr[1])
print(arr[1:3])

20
[20 30]


# Mathematical Operations

In [25]:
a = np.array([10,20,30,40])
b = np.array([50,60,70,80])
print(a+b)
print(a*b)

[ 60  80 100 120]
[ 500 1200 2100 3200]


# Aggregation Function

In [26]:
arr = np.array([10,20,30,40])
print(np.sum(arr))

100


# Reshape array

In [30]:
arr = np.array([10,20,30,40,50,60])
new_arr = arr.reshape(2,3)
print(new_arr)

[[10 20 30]
 [40 50 60]]


# Random numbers

In [31]:
np.random.rand(3)


array([0.94516195, 0.03907258, 0.02336564])

In [34]:
np.random.randint(20,50,5)

array([36, 30, 33, 39, 39], dtype=int32)